HUB-458
marfatech/dto-resolver pull request #3
Opened 2022-09-20 08:47 UTC by Mark-Marfatech

2022-09-20 09:46 UTC, kryakozyablik approved these changes

2022-09-20 10:52 UTC, revilon1991 commented on Dto/DtoResolverTrait.php
>          return $data;
не проще будет чуть дополнить существующий метод?
```php
public function toArray(bool $onlyDefinedData = true, bool $recursive = false): array
{
    $data = $this->getObjectVars();

    if ($onlyDefinedData) {
        $data = $this->getOnlyDefinedData($data);
    }

    if (!$recursive) {
        return $data;
    }

    foreach ($data as $key => $value) {
        if ($value instanceof DtoResolverInterface) {
            $data[$key] = $value->toArray($onlyDefinedData, $recursive);
        }
    }

    return $data;
}
```

2022-09-20 11:21 UTC, revilon1991 commented on Dto/DtoResolverTrait.php
>          return $data;
для коллекций добавить на toArray такие же параметры, а метод выше будет выглядеть так:
```php
public function toArray(bool $onlyDefinedData = true, bool $recursive = false): array
{
    $data = $this->getObjectVars();

    if ($onlyDefinedData) {
        $data = $this->getOnlyDefinedData($data);
    }

    if (!$recursive) {
        return $data;
    }

    foreach ($data as $key => $value) {
        if ($value instanceof DtoResolverInterface) {
            $data[$key] = $value->toArray($onlyDefinedData, $recursive);
        }

        if ($value instanceof CollectionDtoResolverInterface) {
            $data[$key] = $value->toArray($onlyDefinedData, $recursive);
        }
    }

    return $data;
}
```

2022-09-20 12:27 UTC, revilon1991 commented on Dto/DtoResolverTrait.php
>          return $data;
также для массивов
```php
public function toArray(bool $onlyDefinedData = true, bool $recursive = false): array
{
    $data = $this->getObjectVars();

    if ($onlyDefinedData) {
        $data = $this->getOnlyDefinedData($data);
    }

    if (!$recursive) {
        return $data;
    }

    foreach ($data as $key => $value) {
        if ($value instanceof DtoResolverInterface) {
            $data[$key] = $value->toArray($onlyDefinedData, $recursive);
        }

        if ($value instanceof CollectionDtoResolverInterface) {
            $data[$key] = $value->toArray($onlyDefinedData, $recursive);
        }
        
        if (is_array($value)) {
            $data[$key] = array_map(
                fn (DtoResolverInterface $item) => $item->toArray($onlyDefinedData, $recursive),
                $value
            );
        }
    }

    return $data;
}
```

2022-09-20 12:30 UTC, revilon1991 requested changes
- [ ] Обновить changelog
- [ ] Добавить alias на старые интерфейсы и классы без нового параметра для обратно совместимости по примеру [aliases.php](https://github.com/marfatech/api-platform-bundle/pull/5/files#diff-3df835688e417baee6945320be803b7420d4f4b09d64ee6d04f01d4d75db7937) или запланировать [BC] в changelog (в этом случае думаю можно сделать рекурсивность по умолчанию true)

2022-09-29 15:35 UTC, Mark-Marfatech commented on Dto/DtoResolverTrait.php
>          return $data;
Кейс с `CollectionDtoResolverInterface` невозможен, так как для этого нам нужно положить `CollectionDtoResolverInterface` в DTO

2022-09-30 10:55 UTC, revilon1991 requested changes

2022-09-30 11:35 UTC, revilon1991 approved these changes

2022-09-30 14:52 UTC, revilon1991 approved these changes

2022-09-30 14:52 UTC, merged